# These are specific configuration settings required for travis-ci
# see http://travis-ci.org/evendis/travelport
language: ruby
rvm:
  # - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.1.0
  # - rbx-18mode
  # - rbx-19mode
  # - jruby-18mode
  # - jruby-19mode
